config/routes.rb
Cs61asQuizzes::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:edit, :update]

  namespace 'staffs' do

    resources :dashboard, only: :index do
      collection do
        get :import
        post :import_reader
        post :import_gsi
        get :get_passwords
        get :reset_students
        get :reset_staff
      end
    end

    resources :grades do
      collection do
        post :download
        get :download_all
      end
    end

    resources :questions do
      member do
        post :add
      end

      collection do
        get :bank
        get :download
      end
    end

    resources :quiz_requests, only: [:index, :destroy] do
      member do
        post :approve
      end

      collection do
        post :choose
      end
    end

    resources :students, only: [:index, :show] do
      collection do
        get :import
        post :submit_import
        get :download_initial_passwords
      end

      scope module: 'students' do
        resources :quizzes, only: :show do
          put :finish_grading
        end
      end
    end

    resources :taken_quizzes, only: [:update]

    resources :regrades, only: :destroy

    resources :quizzes do
      resource :relationships, only: :destroy

      member do
        get :stats
      end
    end
  end

  namespace 'students' do
    get '/student_dashboard', to: 'dashboard#index', as: :dashboard

    resources :regrades, only: :create

    resources :quizzes, only: [:take, :show] do

      collection do
        get :take
        post :make_request
        post :submit
      end
    end

    resources :quiz_locks, only: [:lock, :unlock] do
      member do
        post :lock
        patch :unlock
      end
    end

    resources :quiz_requests, only: :destroy
  end
end

app/controllers/staffs/base_controller.rb
module Staffs
  class BaseController < ApplicationController
    before_action :authorize_staff!

    private

    def authorize_staff!
      authenticate_user!
      authorize! :manage, :staffs_dashboard
    end
  end
end

app/controllers/staffs/dashboard_controller.rb
# Controller for staff dashboard
module Staffs
  class DashboardController < BaseController

    def index
      @drafts = Quiz.sort_lesson Quiz.drafts, Quiz::DRAFT_LESSON_VALUES
      @published = Quiz.sort_lesson Quiz.published, Quiz::LESSON_VALUES
      @quiz = Quiz.new
      @download = Quiz::LESSON_VALUES.map { |n| ["Lesson #{n}", n] }
    end

    def import
      @results = []
    end

    def import_reader
      @logins = params[:logins]
      @results = @logins.split.
                         reject { |login| Reader.find_by_login login }.
                         map { |login| import_staff login, Reader.new }
      respond_to do |format|
        format.html { redirect_to import_staffs_dashboard_index_path }
        format.csv do
          send_data User.create_csv(@results),
                    filename: 'readers.csv'
        end
      end
    end

    def import_gsi
      @logins = params[:logins]
      @results = @logins.split.
                         reject { |login| Gsi.find_by_login login }.
                         map { |login| import_staff login, Gsi.new }
      respond_to do |format|
        format.html { redirect_to import_staffs_dashboard_index_path }
        format.csv do
          send_data User.create_csv(@results),
                    filename: 'TAs.csv'
        end
      end
    end

    def get_passwords
      reader_passwords = Staff.all.map { |s| [s.login, s.first_password] }
      ta_passwords = Gsi.all.map { |s| [s.login, s.first_password] }
      passwords = reader_passwords + ta_passwords
      respond_to do |format|
        format.html { redirect_to import_staffs_dashboard_index_path }
        format.csv do
          send_data User.create_csv(passwords),
                    filename: "staff_initial_passwords.csv"
        end
      end
    end

    def reset_students
      Student.reset
      flash[:success] = "Reset student database!"
      redirect_to import_staffs_dashboard_index_path
    end

    def reset_staff
      ResetStaffJob.new.async.perform
      flash[:success] = "Reset staff members!"
      redirect_to import_staffs_dashboard_index_path
    end

    private

    def delete_invalid_quizzes
      Quiz.invalid.each { |q| q.destroy }
      true
    end

    def import_staff(login, staff)
      password = Devise.friendly_token.first 8
      staff.update_attributes password: password,
                              first_password: password,
                              login: login
      if staff.new_record?
        [login, "Not saved. #{staff.errors.full_messages.join ' '}"]
      else
        [login, password]
      end
    end
  end
end

app/controllers/staffs/grades_controller.rb
# Controller for Grades
module Staffs
  class GradesController < BaseController
    def index
      @all_to_grade = TakenQuiz.sort_quizzes TakenQuiz.not_graded
      if current_user.reader?
        @assigned = TakenQuiz.sort_quizzes current_user.taken_quizzes.not_graded
      end
    end

    def new
      qid, sid = params[:qid], params[:sid]
      @question = Question.find qid
      @grade = Grade.where(question_id: qid,
                           student_id: sid,
                           lesson: @question.lesson).first_or_create
      redirect_to edit_staffs_grade_path(@grade)
    end

    def edit
      grade = Grade.find params[:id]
      @submission = Submission.find_by question_id: grade.question_id,
                                       student_id: grade.student_id
      @question = Question.find grade.question_id
      @grade_form = EditGradeForm.new grade
      @rlt = Relationship.find_by question: @question,
                                  quiz: @submission.quiz
    end

    def update
      grade = Grade.find params[:id]
      oldg, newg = grade.grade, params[:grade][:grade].to_f
      @submission = Submission.find_by question_id: grade.question_id,
                                       student_id: grade.student_id
      @question = Question.find grade.question_id
      @grade_form = EditGradeForm.new grade
      quiz = Quiz.find(params[:quiz_id])
      if @grade_form.validate_and_save grade_params
        tq = TakenQuiz.find_by student: grade.student, quiz: quiz
        # This needs double checking; isn't really great
        tq.update_attribute(:grade, tq.grade - oldg + newg)
        redirect_to staffs_student_quiz_path(grade.student_id, quiz)
      else
        @rlt = Relationship.find_by question_id: @question,
                                    quiz_id: @submission.quiz_id
        render 'edit'
      end
    end

    def download
      respond_to do |format|
        format.html { redirect_to staffs_dashboard_path }
        format.csv do
          send_data Student.get_csv(params[:lesson]),
                    filename: "lesson#{params[:lesson]}.csv"
        end
      end
    end

    def download_all
      respond_to do |format|
        format.csv do
          t = get_all_grades
          send_file t.path, filename: 'grades.zip',
                            type: 'application/zip',
                            disposition: 'attachment'
        end
      end
    end

    private

    def grade_params
      params.require(:grade).permit!
    end

    def get_all_grades
      files = Quiz::LESSON_VALUES.map do |q|

      end
      t = Tempfile.new(["my-temp-filename-#{Time.now}", '.zip'])
      Zip::File.open(t.path, Zip::File::CREATE) do |zipfile|
        Quiz::LESSON_VALUES.drop(1).each do |lesson|
          zipfile.get_output_stream("lesson#{lesson}.csv") do |f|
            f.write Student.get_csv(lesson)
          end
        end
        # zipfile.get_output_stream("myFile.,txt") { |os| os.write "myFile contains just this" }
      end
      t.close
      t
      # Zip::ZipOutputStream.open(t.path) do |zipfile|
      #   1/0
      #   Quiz::LESSON_VALUES.each do |lesson|
      #       zipfile.put_next_entry lesson
      #       zipfile.write Student.get_csv(lesson)
      #   end
      # end
      # t.close
    end
  end
end

app/controllers/staffs/questions_controller.rb
# Question Controller
module Staffs
  class QuestionsController < BaseController
    before_action :set_question, only: [:edit, :update, :destroy, :add]

    def new
      if params[:quiz_id]
        @quiz_id = params[:quiz_id]
        @quiz = Quiz.find params[:quiz_id]
        question = @quiz.questions.new lesson: @quiz.lesson
        @add_pts = 'true'
      else
        question = Question.new
        @add_pts = 'false'
      end
      @lesson = 'true'
      question.solution = Solution.new
      question.rubric = Rubric.new
      @quest_form = NewQuestionForm.new question
    end

    def create
      quiz = assign_params
      question = CreateQuestion.call question_params.except :points
      @quest_form = NewQuestionForm.new question
      if @quest_form.validate_and_save question_params
        flash[:success] = 'Created Question!'
        redirect_after_editing quiz
      else
        render 'new'
      end
    end

    def index
      @lessons = Quiz::LESSON_VALUES
    end

    def show
      @question = Question.find params[:id]
    end

    def edit
      get_question_options
      @quest_form = EditQuestionForm.new @question
      rlt = Relationship.find_by(quiz_id: params[:quiz_id],
                                 question: @question)
      @points = rlt.nil? ? 0 : rlt.points
    end

    def update
      quiz = assign_params
      @quest_form = EditQuestionForm.new @question
      if @quest_form.validate_and_save question_params
        flash[:success] = 'Updated Question!'
        redirect_after_editing quiz
      else
        render 'edit'
      end
    end

    def destroy
      quizzes = @question.quizzes
      if quizzes.blank?
        @question.destroy
        flash[:success] = 'Deletion successful!'
      else
        used_by = quizzes.map(&:to_s).join ', '
        flash[:error] = "This question is being used by the following quizzes: #{used_by}. Please remove the question on the quiz(zes) first."
      end
      redirect_to :back
    end

    def bank
      @questions = Question.where(lesson: params[:lesson])
                           .includes(:solution).includes(:rubric)
                           .page params[:page]
      @requests = QuizRequest.all
      @add = params[:add] == 'true'
      @id = params[:quiz_id]
    end

    def add
      @quiz = Quiz.find params[:quiz_id]
      if @quiz.can_add? @question
        Relationship.where(question: @question, quiz: @quiz).first_or_create
        flash[:success] = 'Added question from question bank!'
      else
        @lesson = Quiz::LESSON_VALUES
        flash[:error] = 'This question has already been used on a retake!'
      end
      redirect_to edit_staffs_quiz_path @quiz
    end

    def download
      file = Tempfile.new('questions')
      Question.get_assigned_questions.each do |q|
        file.puts "Lesson: #{q.lesson} \n"
        file.puts "Difficulty: #{q.difficulty}\n"
        file.puts "Content:\n#{q.content.truncate 100 } \n\n"
        file.puts "Solution:\n#{q.solution.content}\n\n"
        file.puts "Rubric:\n#{q.rubric.rubric}\n\n"
        file.puts "Total Points: #{q.relationships.first.points}\n\n"
        file.puts "Average Points: #{q.get_average}\n\n\n\n"
      end
      send_file file, filename: 'questions.md'
      file.close
    end

    private

    def set_question
      @question = Question.find params[:id]
    end

    # Bad - explicitly require params
    def question_params
      params.require(:question).permit!
    end

    def redirect_after_editing(quiz)
      if quiz
        redirect_to edit_staffs_quiz_path(quiz)
      else
        redirect_to staffs_questions_path
      end
    end

    def assign_params
      get_question_options
      @points = params[:points]
      question_params[:points] = { pts: @points, qid: @quiz_id }
      quiz = Quiz.find_by_id @quiz_id
    end

    def get_question_options
      @add_pts, @lesson, @quiz_id = params[:add_pts], params[:lesson], params[:quiz_id]
    end
  end
end

app/controllers/staffs/quiz_requests_controller.rb
# Controller for approving/cancelling quiz requests
module Staffs
  class QuizRequestsController < BaseController
    before_action :set_quiz_request, only: [:approve, :choose]

    def index
      @requests = QuizRequest.all
      @regrades = Regrade.not_graded
    end

    def choose
      @quiz_request.lock_and_destroy! params[:quiz_id], params[:quiz_time]
      approve_flash
    end

    def destroy
      request = QuizRequest.find_by_id(params[:id])
      if request
        request.destroy
      end
      flash[:success] = 'Cancelled quiz request!'
      redirect_to staffs_dashboard_path
    end

    private

    def set_quiz_request
      @quiz_request = QuizRequest.find params[:id]
    end

    def approve_flash
      flash[:success] = "Approved #{@quiz_request.student}!"
      redirect_to staffs_quiz_requests_path
    end
  end
end

app/controllers/staffs/quizzes_controller.rb
# Controller for quizzes
module Staffs
  class QuizzesController < BaseController
    before_action :set_quiz, only: [:edit, :update, :show]

    def new
      @new_quiz = Quiz.create
      redirect_to edit_staffs_quiz_path(@new_quiz), notice: 'Created Quiz'
    end

    def create
      if params[:quiz][:quiz_type]
        if params[:quiz][:lesson].empty?
          redirect_to :back, notice: 'Invalid Lesson Number'
        else
          lesson, rtk = params[:quiz][:lesson], params[:quiz][:retake]
          @quiz = Quiz.generate_random(lesson, rtk)
          redirect_to edit_staffs_quiz_path(@quiz), notice: 'Created quiz.'
        end
      end
    end

    def edit
      @quiz_form = EditQuizForm.new @quiz
      @questions = @quiz.questions
      @lessons = Quiz::LESSON_VALUES
      Question.destroy(params[:destroy]) if params[:destroy]
      respond_to do |format|
        format.html { render 'edit' }
        format.js {}
      end
    end

    def update
      @quiz_form = EditQuizForm.new @quiz
      @questions = @quiz.questions
      @lessons = Quiz::LESSON_VALUES
      if @quiz_form.validate_and_save quiz_params
        flash[:success] = "Updated #{@quiz}!"
        redirect_to staffs_dashboard_path
      else
        render :edit
      end
    end

    def destroy
      Quiz.destroy params[:id]
      redirect_to staffs_dashboard_path, notice: 'Deleted quiz.'
    end

    def show
      @questions = @quiz.questions
    end

    def stats
      @quiz = Quiz.find(params[:id])
      @grades = TakenQuiz.where(quiz: @quiz, finished: true)
      @students, @avg = [], 0.0
      @grades.each do |g|
        s = Student.find(g.student_id)
        @students << [s.name, s.login, g.grade]
        @avg += g.grade
      end

      @avg /= (@grades.length.nonzero? || 1)
    end

    private

    def set_quiz
      @quiz = Quiz.includes(:questions).find(params[:id])
    end

    def quiz_params
      params.require(:quiz).permit!
    end
  end
end

app/controllers/staffs/regrades_controller.rb
module Staffs
  class RegradesController < BaseController
    def destroy
      @regrade = Regrade.destroy params[:id]
      TakenQuiz.find_by(student: @regrade.student_id,
                        quiz: @regrade.quiz_id).finish
      flash[:success] = "You've deleted the regrade request.
                         The student can now request another one"
      redirect_to staffs_dashboard_path
    end
  end
end

app/controllers/staffs/relationships_controller.rb
module Staffs
  class RelationshipsController < BaseController
    def destroy
      quiz = Quiz.find params[:quiz_id]
      if quiz.is_draft?
        Relationship.find_by(quiz: quiz, question_id: params[:question_id]).destroy
        flash[:success] = "Removed question from quiz."
      else
        flash[:error] = "Can't remove question from published quiz!"
      end
      redirect_to edit_staffs_quiz_path quiz
    end
  end
end

app/controllers/staffs/students/quizzes_controller.rb
module Staffs::Students
  class QuizzesController < Staffs::BaseController
    def show
      @quiz = Quiz.find params[:id]
      @student = Student.find params[:student_id]
      @questions = @quiz.questions
      @subm = @questions.map { |q| q.submissions.find_by student: @student }
      @scores = @questions.map { |q| q.grades.find_by student: @student }
      @ques_subm = QuizSubmission.new(@questions, @subm, @scores).ques_subm
      @grade = TakenQuiz.find_by quiz: @quiz, student: @student
      @request = Regrade.find_by quiz: @quiz, student: @student
      @not_graded = @scores.inject(false) { |q, q2| q || q2.nil? }
    end

    def finish_grading
      student, quiz = params[:student_id], params[:quiz_id]
      TakenQuiz.find_by(student_id: student, quiz_id: quiz).finish
      Student.find(params[:student_id]).check_if_send_email
      regrade = Regrade.find_by(student_id: student, quiz_id: quiz)
      regrade.finish if regrade
      flash[:success] = 'Finished grading!'
      redirect_to staffs_grades_path
    end
  end
end

app/controllers/staffs/taken_quizzes_controller.rb
module Staffs
  class TakenQuizzesController < BaseController
    def update
      @taken_quiz = TakenQuiz.find params[:taken_quiz].delete :taken_id
      if @taken_quiz.update_attributes taken_quiz_params
        flash[:notice] = 'Added changes!'
      else
        flash[:error] = 'Invalid login or comment.'
      end
      redirect_to staffs_student_quiz_path(@taken_quiz.student,
                                           @taken_quiz.quiz)
    end

    private

    def taken_quiz_params
      params.require(:taken_quiz).permit!
    end
  end
end

app/views/staffs/dashboard/grading.html.slim
h3 Quizzes To Grade

h4 Your Grading Assignments

- if @assigned.empty?
  p You have no assignments. Go have fun ^^. Or do more homework.
- else
  ul
    - @assigned.each do |g|
      li
        = link_to g, student_quiz_path(g.student, g.quiz)


h4 All Quizzes to Grade

- if @all_to_grade.empty?
  p There are no quizzes to grade! Way to Go!
- else
  ul
    - @all_to_grade.each do |g|
      li
        = link_to g, student_quiz_path(g.student, g.quiz)

app/views/staffs/dashboard/import.html.slim
h4 Create TAs
= form_tag import_gsi_staffs_dashboard_index_path(format: 'csv') do
  .row
    .medium-7.columns
      = label_tag :logins, 'Copy and paste TA logins, one per line. You may enter in logins that have already been processed before; they will be ignored. TA logins must begin with the letter "t".'
      = text_area_tag :logins, @logins, class: 'expand', id: "import"
  .row
    .medium-12.columns
      = submit_tag 'Create TAs', class: 'button'

h4 Create Readers
= form_tag import_reader_staffs_dashboard_index_path(format: 'csv') do
  .row
    .medium-7.columns
      = label_tag :logins, 'Copy and paste student logins, one per line. You may enter in logins that have already been processed before; they will be ignored.'
      = text_area_tag :logins, @logins, class: 'expand', id: "import"
  .row
    .medium-12.columns
      = submit_tag 'Create Readers', class: 'button'


.row
  .columns
    p Click here to download initial passwords for all staff members!

    = link_to 'Download Passwords', get_passwords_staffs_dashboard_index_path(format: 'csv'),
                                    class: 'button'


h1 DANGEROUS TERRITORY - BE CAUTIOUS

.row
  .columns
    p Reset all Students - This will wipe the database of all students, grades, quizzes taken, etc.
    = link_to "Reset Students", reset_students_staffs_dashboard_index_path,
                                class: 'button', data: { confirm: "Are you SURE?!?! Changes cannot be undone!" }

.row
  .columns
    p Reset all Staff - This will wipe the database of all staff members!
    = link_to "Reset Staff", reset_staff_staffs_dashboard_index_path,
                             class: 'button', data: { confirm: "Are you SURE?!?!, Changes cannot be undone!" }

app/views/staffs/dashboard/import_students_form.html.slim
h3 Import Students
= form_tag import_students_path(format: 'csv') do
  .row
    .medium-7.columns
      = label_tag :logins, 'Copy and paste student logins, one per line. You may enter in logins that have already been processed before; they will be ignored.'
      = text_area_tag :logins, @logins, class: 'expand'
  .row
    .medium-12.columns
      = submit_tag 'Create students!', class: 'button'

.row
  .columns
    - unless @results.empty?
      h3 Results:
      - @results.each do |login, password|
        = "#{login},#{password}"
        br

.row
  .columns
    p Click here to download initial passwords for all currently registered students!

    = link_to 'Download Passwords', download_pw_path(format: 'csv'), 
                                    class: 'button'

app/views/staffs/dashboard/index.html.slim
h1 Welcome to the Staff Dashboard!

p.makequizzes
  = link_to "Create a New Quiz!", new_staffs_quiz_path, class: 'button small'

p or

h3 Generate a quiz

.row
  .small-3.columns
    = simple_form_for @quiz, url: staffs_quizzes_path do |f|
      = f.hidden_field :quiz_type, value: 'generate'
      = f.input :lesson, collection: Quiz::LESSON_VALUES
      = f.input :retake, as: :boolean, label: 'Retake?'
      = f.submit 'Generate!', class: 'button small'

h3 Quiz Drafts
ul.quizzes
  - @drafts.each do |quiz|
    li = link_to quiz, staffs_quiz_path(quiz)
    ul = link_to 'Delete Quiz', staffs_quiz_path(quiz),
                                method: :delete,
                                data: { confirm: "You sure?" }

h3 Published Quizzes
ul.quizzes
  - @published.each do |quiz|
    li = link_to quiz, staffs_quiz_path(quiz)


h3 Download Grades.txt file
.row
  .small-3.column
    = form_tag download_staffs_grades_path(format: 'csv') do
      = select_tag :lesson, options_for_select(@download)
      = submit_tag 'Download!', class: 'button'

.row
  .small-3.column
    = link_to "Download All Grades!", download_all_staffs_grades_path(format: 'csv') , class: "button"

app/views/staffs/dashboard/questions.html.slim
h3 Add a Question!

= link_to 'New Question!', new_question_path(id: nil)

h3 Question Bank:

= render 'question_bank', lesson: @lessons,
                          add: false,
                          quiz_id: nil

h3 Download All Questions

= link_to 'Download!', download_questions_path, class: 'button'

app/views/staffs/dashboard/requests.html.slim
h3 Quiz Requests

- if @requests.empty?
  p You don't have any quiz requests!
- else
  ul.quiz-requests
    - @requests.each do |request|
      li
        = request
        = link_to '  Approve  ', approve_quiz_request_path(request),
                  method: :post, id: "approve-#{request.id}"

        = link_to 'Cancel', quiz_request_path(request),
                  method: :delete, id: "cancel-#{request.id}"

h3 Quiz Regrade Requests

- if @regrades.empty?
  p You don't have any regrade requests!
- else
  ul
    - @regrades.each do |re|
      li
        = link_to re, student_quiz_path(re.student, re.quiz)
        = link_to "Delete Request!", regrade_path(re), method: :delete

app/views/staffs/dashboard/students.html.slim
h3 Students

div
  row
    .small-12.columns
      p Search
      = form_for students_dashboard_path, method: 'get' do
        = text_field_tag :search, @value, placeholder: 'Enter a name!'
        = submit_tag 'Search!', class: 'small button'
div
  row 
    .small-12.columns
      p Search Results
      ul
        - if @search.blank?
          p No Results!
        - else
          - @search.each do |student|
            li = link_to student, student
div
  row
    .small-12.columns
      p All Students
      ul.students
        - @students.each do |student|
          li = link_to student, student

        = paginate @students