config/routes.rb
Cs61asQuizzes::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:edit, :update]

  namespace 'staffs' do

    resources :dashboard, only: :index do
      collection do
        get :import
        post :import_reader
        post :import_gsi
        get :get_passwords
        get :reset_students
        get :reset_staff
      end
    end

    resources :grades do
      collection do
        post :download
        get :download_all
      end
    end

    resources :questions do
      member do
        post :add
      end

      collection do
        get :bank
        get :download
      end
    end

    resources :quiz_requests, only: [:index, :destroy] do
      member do
        post :approve
      end

      collection do
        post :choose
      end
    end

    resources :students, only: [:index, :show] do
      collection do
        get :import
        post :submit_import
        get :download_initial_passwords
      end

      scope module: 'students' do
        resources :quizzes, only: :show do
          put :finish_grading
        end
      end
    end

    resources :taken_quizzes, only: [:update]

    resources :regrades, only: :destroy

    resources :quizzes do
      resource :relationships, only: :destroy

      member do
        get :stats
      end
    end
  end

  namespace 'students' do
    get '/student_dashboard', to: 'dashboard#index', as: :dashboard

    resources :regrades, only: :create

    resources :quizzes, only: [:take, :show] do

      collection do
        get :take
        post :make_request
        post :submit
      end
    end

    resources :quiz_locks, only: [:lock, :unlock] do
      member do
        post :lock
        patch :unlock
      end
    end

    resources :quiz_requests, only: :destroy
  end
end

app/views/shared/_flash.html.slim
<script type="text/javascript">
  - flash.each do |key, val|
    | toastr.#{key}("#{val}")
</script>

app/views/shared/_ga_boiler.html.slim
/ Fill in later with GA

app/views/shared/_header.html.slim
nav.top-bar data-topbar=true
  ul.title-area
    li.name
      - if current_user.nil?
        h1 = link_to 'CS61AS Quizzes', root_path
      - elsif current_user.staff?
        h1 = link_to 'Dashboard', staffs_dashboard_index_path
      - elsif current_user.student?
        h1 = link_to 'Dashboard', students_dashboard_path
  section.top-bar-section
    - if current_user && current_user.staff?
      ul.left
        li.divider
        li = link_to 'Questions', staffs_questions_path
        li.divider
        li = link_to 'Students', staffs_students_path
        li.divider
        li = link_to 'Requests', staffs_quiz_requests_path
        li.divider
        li = link_to 'Grading', staffs_grades_path
        li.divider
        li = link_to 'Import Students', import_staffs_students_path
        li.divider
        - if @current_user.master?
          li = link_to 'Import Staff', import_staffs_dashboard_index_path
          li.divider
    ul.right
      li.divider
      - if current_user
        - if !current_user.taking_quiz?
          li.has-dropdown
            = link_to "Account", '#'
            ul.dropdown
              li = link_to ' Edit Profile', edit_user_path(current_user)
              li = link_to 'Sign Out', destroy_user_session_path, method: :delete
      - else
        li = link_to 'Sign In', new_user_session_path

app/views/shared/_markdown_reference.html.slim
.row.md-ref
  .small-12.columns
    .row
      .medium-6.columns
        h3 This Markdown...
      .medium-6.columns
        h3 produces this output
    .row
      .medium-6.columns
        pre
          | # This is an h1
      .medium-6.columns
        = markdown '# This is a h1'
    .row
      .medium-6.columns
        pre
          | # This is an h3
      .medium-6.columns
        = markdown '### This is a h3'
    .row
      .medium-6.columns
        pre
          | > This is a blockquote.
      .medium-6.columns
        = markdown '> This is a blockquote.'
    .row
      .medium-6.columns
        pre
          | *These words* are emphasized.
      .medium-6.columns
        = markdown '*These words* are emphasized.'
    .row
      .medium-6.columns
        pre
          | **So are these**
      .medium-6.columns
        = markdown '**So are these**'
    .row
      .medium-6.columns
        pre
          | ==These words== will be highlighted.
      .medium-6.columns
        = markdown '==These words== will be highlighted.'
    .row
      .medium-6.columns
        pre
          | - This is an unordered list element.
          br
          | - This is another unordered list element.
      .medium-6.columns
        = markdown "- This is an unordered list element.\n\
                    - This is another unordered list element."
    .row
      .medium-6.columns
        pre
          | 1. This is an ordered list element.
          br
          | 2. This is another ordered list element.
      .medium-6.columns
        = markdown "1. This is an ordered list element.\n\
                    2. This is another ordered list element."
    .row
      .medium-6.columns
        pre
          | `Backticks` denote inline code.
      .medium-6.columns
        = markdown '`Backticks` denote inline code.'
    .row
      .medium-6.columns
        pre
          |     This is a code block. (4 spaces)
        p
      .medium-6.columns
        = markdown '    This is a code block. (4 spaces)'
    .row
      .medium-6.columns
        pre
          | ``` scheme
          br
          | (define (scheme-example x)
          br
          |   'this-is-scheme-code)
          br
          | ```
      .medium-6.columns
        = markdown "``` scheme\n\
                    (define (scheme-example x)\n  \
                    'this-is-scheme-code)\n\
                    ```"
    br
    ' Check out the #{link_to 'syntax', 'http://daringfireball.net/projects/markdown/syntax#code'}
    | for more details.

app/views/shared/_show_answers.html.slim
- ques_subm.each do |question, subm, score, rlt|
  div
    p = "Question #{rlt.number}:"
    p = markdown question.content
    p Student Answer:
    textarea.show
      = subm.content
    - if score && (current_user.staff? || grade.finished)
      p Grade:
      p = score.grade
      p Points Possible:
      p = rlt.points
      p Reader Comments:
      p = markdown score.comments
    br
    - if current_user.staff?
      = link_to 'Grade Question!', new_staffs_grade_path(qid: question.id,
                                                  sid: student.id),
                                   class: 'small button',
                                   id: "grade#{question.id}"